name: Feature Request
description: Suggest a new feature for Grow Room Manager
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature!

  - type: textarea
    id: description
    attributes:
      label: Feature description
      description: A clear description of the feature you'd like.
    validations:
      required: true

  - type: textarea
    id: use-case
    attributes:
      label: Use case
      description: Describe the problem this feature would solve.
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
      description: Any alternative solutions you've considered.
